language: bash

dist: xenial

services:
  - docker

before_script:
  - echo "pyu@#$56" | docker login -u "pyu12" --password-stdin

script:
  - echo "test xXXXXxxXXXxxXXXxxx  code"

after_success:
  - docker build -t username/alpine .
  - docker push username/alpine
